# tab-separated file of the samples
#samples: samples.tsv
samples: samples.tsv

# pipeline file locations
#result_dir: ./results_gene_names # where to store results
result_dir: ./scRNAseq # where to store results

#genome_dir: ./genomes  # where to look for or download the genomes

#genome_dir: /ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/genomepy_genomes
genome_dir: ./genomes
fastq_dir: ./fastq # where to look for fastqs
# contact info for multiqc report and trackhub
email: jsmits@science.ru.nl

fqext1: R1
fqext2: R2

# how to handle replicates
technical_replicates: merge

#to get gene names instead of transcript/gene IDs
provider: NCBI


# scRNA options
# seq2science does currently not support scrna-seq platforms that generate more than two fastq files, such as 10xv1.
quantifier:
  kallistobus:
    ## Velocity example ##
    ref: '--workflow lamanno'
    count: '-x 1,8,16:1,0,8:0,0,0 --verbose --workflow lamanno --loom'
sc_preprocess:
   export_sce_objects: False
   run_sctk_qc: True
   sctk_data_type: cell
   use_alt_expr: False
   alt_exp_name: ""
   alt_exp_reg: ""
   sctk_mito_set: human-symbol
   sctk_detect_mito: False
   sctk_detect_cell: False
   sctk_cell_calling: Knee
   velo_assay: spliced
   sctk_qc_algos: ["scDblFinder", "decontX"]


custom_annotation_extension: /ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/scRNAseq_iPSC_iLSCs/genomes/spike_in/ERC_92_name_biotype_ext.gtf
custom_genome_extension: /ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/scRNAseq_iPSC_iLSCs/genomes/spike_in/ERCC92_v2.fa
custom_assembly_suffix: "ERCCreporter"
barcodefile: "/ceph/rimlsfnwi/data/moldevbio/zhou/jsmits/tools/1col_barcode_384.tab"
